image_width: 1280
image_height: 720
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [461.05775,   0.     , 703.39216,
           0.     , 461.19033, 375.24809,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.000243, -0.020521, -0.002063, -0.004926, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [439.76599,   0.     , 670.90934,   0.     ,
           0.     , 460.54977, 374.72691,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
